"use strict";

exports.REGISTERACCOUNT = "REGISTERACCOUNT";
exports.VERIFYTOKEN = "VERIFYTOKEN";
exports.GENERATETOKEN = "GENERATETOKEN";
exports.LOGIN = "LOGIN";
exports.LISTACCOUNTS = "LISTACCOUNTS";
exports.FORGOTPASSWORD = "FORGOTPASSWORD";
exports.CHANGEPASSWORD = "CHANGEPASSWORD";
exports.RESETPASSWORD = "RESETPASSWORD";
exports.DELETEACCOUNT = "DELETEACCOUNT";
exports.GET_GOOGLE_SIGNIN_URL = "GET_GOOGLE_SIGNIN_URL";
exports.GOOGLE_SIGNUP = "GOOGLE_SIGNUP";