"use strict";

exports.REGISTERACCOUNT = "REGISTERACCOUNT";
exports.VERIFYTOKEN = "VERIFYTOKEN";
exports.GENERATETOKEN = "GENERATETOKEN";
exports.LOGIN = "LOGIN";
exports.LISTACCOUNTS = "LISTACCOUNTS";
exports.FORGOTPASSWORD = "FORGOTPASSWORD";
exports.CHANGEPASSWORD = "CHANGEPASSWORD";
exports.RESETPASSWORD = "RESETPASSWORD";
exports.DELETEACCOUNT = "DELETEACCOUNT";